version: '3.8'

services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DOCKER_ENV=true
    profiles: ["frontend", "dev"]
    tty: true

  # Backend service
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/backend:/app/src/backend
      - /app/src/backend/node_modules
      - /app/src/backend/dist
    environment:
      - NODE_ENV=development
    profiles: ["backend", "dev"]
    tty: true
    working_dir: /app/src/backend

  # Full stack service (frontend + backend in one container)
  fullstack:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/src/backend/node_modules
      - /app/src/backend/dist
    environment:
      - NODE_ENV=production
      - DOCKER_ENV=true
    profiles: ["fullstack"]
    tty: true

  # Production environment
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
    volumes:
      - ./todos.db:/etc/nginx/todos.db
    profiles: ["prod"]
    restart: unless-stopped