# Use Node.js 20 as the base image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install frontend dependencies
RUN npm install --prefer-offline --no-audit --no-fund && \
    npm cache clean --force && \
    rm -rf /root/.npm/_cacache

# Copy the rest of the application code
COPY . .

# Expose frontend port
EXPOSE 5173

# Start the development server
CMD ["npm", "run", "dev", "--", "--host"]